#ifndef TIOO_CABLEGRAM_ERRORS_H_
#define TIOO_CABLEGRAM_ERRORS_H_

#define CABLEGRAM_ERROR_PROGRAM_ID_OUT_OF_BOUNDS    (-1)
#define CABLEGRAM_ERROR_QUEUE_IS_FULL               (-2)

#endif //TIOO_CABLEGRAM_ERRORS_H_
