#ifndef TIOO_SYNCHRONIZER_ERRORS_H_
#define TIOO_SYNCHRONIZER_ERRORS_H_

#define SYNCHRONIZER_ERROR_ID_OUT_OF_BOUNDS             (-1)
#define SYNCHRONIZER_ERROR_THERE_IS_NO_FREE_SLOTS       (-2)
#define SYNCHRONIZER_ERROR_WRONG_TYPE                   (-3)
#define SYNCHRONIZER_ERROR_OBJECT_IS_ALREADY_FREE       (-4)
#define SYNCHRONIZER_ERROR_RESOURCE_NOT_USED            (-5)
#define SYNCHRONIZER_ERROR_RESOURCE_YOU_ARE_NOT_OWNER   (-6)

#endif //TIOO_SYNCHRONIZER_ERRORS_H_
